In [ ]:
import numpy as np
arr = np.array([10,20,30,40,50])
print(arr)

In [ ]:
import numpy as np
arr=np.array([10,20,30,40,50],dtype=complex)
print(arr)

In [ ]:
import numpy as np
lists1=[[101,202,303],[404,505,606]]
arr1=np.array(lists1)
print("数组arr1的数据类型是：")
print(arr1.dtype)
print("数组arr1的数组形状是：")
print(arr1.shape)

In [ ]:
import numpy as np
arr1=np.zeros((3,4))
print(arr1)

In [ ]:
import numpy as np
arr1=np.ones((3,4))
print(arr1)

In [ ]:
import numpy as np
arr1=np.identity(3)
print(arr1)

In [ ]:
import numpy as np
arr1=np.empty((4,4))
print(arr1)

In [ ]:
import numpy as np
arr1=np.array([12.5,136.7,24.6,35.5,109.8])
int_arr1=arr1.astype(int)
print(int_arr1.dtype)
print(int_arr1)
str_arr1=arr1.astype(str)
print(str_arr1.dtype)
print(str_arr1)

In [ ]:
import numpy as np
samples=np.random.normal(size=(4,4))
print(samples)

In [ ]:
from random import normalvariate
import time
import numpy as np
n=10000000
start = time.time()
samples = [normalvariate(0,1) for _ in range(n)]
time1 = time.time() - start
print(time1)

start = time.time()
times = np.random.normal(size = n)
time2 = time.time()-start
print(time2)

In [ ]:
import numpy as np
arr1=np.array([[10,20,30],[7,8,9]])
multi_arr=arr1*arr1
sub_arr=arr1-arr1
print("大小相等的数组实现乘法")
print(multi_arr)
print("大小相等的数组实现减法")
print(sub_arr)

In [ ]:
import numpy as np
arr1=np.array([[10,20,30],[7,8,9]])
divide_arr=100/arr1
multi_arr=arr1*0.5
print("数组与标量值的除法运算")
print(divide_arr)
print("数组与标量值的乘法运算")
print(multi_arr)

In [ ]:
import numpy as np
weathers=np.array([[20,21,22,18,19,21,22],[18,21,23,19,18,21,13],
[18,19,22,21,21,17,16],[15,
18,20,19,21,17,18]])
print(weathers.mean(0))
meaned=weathers-weathers.mean(0)
print(meaned)
print(meaned.mean(0))

In [ ]:
import numpy as np
weathers=np.array([[20,21,22,18,19,21,22],[18,21,23,19,18,21,13],
[18,19,22,21,21,17,16],[15,18,
20,19,21,17,18]])
print(weathers.mean(1).reshape((4,1)))
meaned=weathers-weathers.mean(1).reshape((4,1))
print(meaned)
print(meaned.mean(1))

In [ ]:
import numpy as np
arr=np.array([3.1,3.14,3.141,3.1415,3.14159,3.141592,3.1415926])
print(arr[4])
print("------------------")
print(arr[3:6])
print("------------------")
arr[3:6]=3.14159265358
print(arr)

In [ ]:
import numpy as np
arr=np.array([[[3.1,3.14],[3.141,3.1415]],[[3.14159,3.141592],
[3.1415926,3.14159265]]])
print(arr.shape)
print(arr[1])
print("-----------------")
print(arr[1,0])

In [ ]:
import numpy as np
arr=np.array([[[3.1,3.14],[3.141,3.1415]],[[3.14159,3.141592],
[3.1415926,3.14159265]]])
print(arr[-1])

In [ ]:
import numpy as np
names=np.array(["业务员","业务员","经理","主管","业务员","主管"])
salary=np.array([2520.00,3600.00,2745.00,4200.00,3805.00,3947.00])
print(salary[names=="经理"])

In [ ]:
import numpy as np
arr=np.array([[1,1,1,1,1],[2,2,2,2,2],[3,3,3,3,3],[4,4,4,4,4],
[5,5,5,5,5]])
print(arr)
arr_trans=arr.transpose()
print(arr_trans)

In [ ]:
import numpy as np
arr=np.array([[1,1,1,1,1],[2,2,2,2,2],[3,3,3,3,3],[4,4,4,4,4],
[5,5,5,5,5]])
arr_trans=arr.T
print(arr_trans)

In [ ]:
import numpy as np
arr=np.random.randn(4,)
print(arr)
result=np.dot(arr.T,arr)
print(result)

In [ ]:
import numpy as np
arr=np.arange(16).reshape(2,2,4)
print(arr)
trans_arr=arr.transpose(1,0,2)
print("-----------")
print(trans_arr)

In [31]:
import numpy as np
arr1=np.array([3])
repeat_arr1=arr1.repeat(3)
print(repeat_arr1)
print("------------------------------")
arr2=np.eye(3)
repeat_arr2=arr2.repeat(3)
print(repeat_arr2)
print("------------------------------")
arr3=np.eye(3)
repeat_arr3=arr3.repeat(3,axis=0)
print(repeat_arr3)

[3 3 3]
------------------------------
[1. 1. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 1. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 1. 1. 1.]
------------------------------
[[1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]]


In [32]:
import numpy as np
arr=np.eye(3)
repeat_arr=np.tile(arr,3)
print(repeat_arr)

[[1. 0. 0. 1. 0. 0. 1. 0. 0.]
 [0. 1. 0. 0. 1. 0. 0. 1. 0.]
 [0. 0. 1. 0. 0. 1. 0. 0. 1.]]
