In [ ]:
import numpy as np
arr = np.array([10,20,30,40,50])
print(arr)

In [ ]:
import numpy as np
arr=np.array([10,20,30,40,50],dtype=complex)
print(arr)

In [ ]:
import numpy as np
lists1=[[101,202,303],[404,505,606]]
arr1=np.array(lists1)
print("数组arr1的数据类型是：")
print(arr1.dtype)
print("数组arr1的数组形状是：")
print(arr1.shape)

In [16]:
import numpy as np
arr1=np.zeros((3,4))
print(arr1)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [17]:
import numpy as np
arr1=np.ones((3,4))
print(arr1)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [18]:
import numpy as np
arr1=np.identity(3)
print(arr1)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [20]:
import numpy as np
arr1=np.empty((4,4))
print(arr1)

[[2.23882404e-316 0.00000000e+000 2.41907520e-312 2.37663529e-312]
 [2.22809558e-312 2.46151512e-312 6.79038654e-313 2.35541533e-312]
 [2.46151512e-312 6.79038654e-313 2.35541533e-312 6.79038654e-313]
 [2.14321575e-312 2.22809558e-312 2.14321575e-312 0.00000000e+000]]
